spring:
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    bus:
      enabled: true  

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,refresh
      discovery:
        enabled: true
      base-path: /sys
  endpoint:
    health:
      enabled: true
    refresh:
      enabled: true
      