user:
  role: SuperDuperDeveloper112

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,refresh,metrics,prometheus
      discovery:
        enabled: true
      base-path: /sys
  endpoint:
    health:
      enabled: true
    refresh:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true




