user:
  role: NotSoSuperDuperOldBuddy

com:
  lazyboyprod:
    event:
      specification: new-spec

      supported:
        - hello
        - bye
        - buy
        - add
        - remove
        - check

